#Plik configu do pluginu KoTools

#Czy wlaczyc funkce kontrolu nad chatem true - tak/falne - nie
enableChatControl: true

#Wlancza uderzenie piorunem po smierci gracza true - tak/falne - nie
enableLightning: true

#Czy wlaczyc uzywanie motd z poziomu pluginu
useMotd: true

#Wiadomosc motd
msgMotd: '&8[&6KoTools&8] &cS&fW&cI&fA&cT&fE&cC&fZ&cN&fA &cE&fD&cY&fC&cJ&fA &cN&fA&cD&fC&cH&fO&cD&fZ&cI &c&l&m-&f&l&m-&c&l&m-&f&l&m-&c&l&m-&f &7Start: &bSroda 18:00 &7Najlepsza Edycja! &c&l&m-&f&l&m-&c&l&m-&f&l&m-&c&l&m-'

#Czy wlaczyc ustawianie ilosci graczy (nie prawdziwe)
useFakePlayers: true

#Liczba graczy fake
fakePlayers: 2017

#Czy uzywac ikony serwera
useServerIcon: false

#Czy wlaczyc automatycze wiadomosci true - tak/falne - nie
enableAutoMsg: true

#Czas generacji stone
stoneGeneratorTimeToRegenerate: 20

#Czas po ktorej wlanczasie kolejna wiadomosc
autoMsgTime: 120
listMsg:
  - '&8[&6KoTools&8] &8Wiadomosc testowa #1'
  - '&8[&6KoTools&8] &8Wiadomosc testowa #2'
  - '&8[&6KoTools&8] &8Wiadomosc testowa #3'
  
#Czy ma automatycznie przenosic w random kordy
randomowe_miejsce_po_wejsciu: true
  
      



##########################
#                        #
# Funkcje nie dokonczone #
#                        #
##########################
